//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestingKofaxIssues.neikofaxccmdev {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ITPInTheCloud", Namespace="http://www.aiasoftware.com/cloud/v1")]
    public partial class ITPCloudService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateDocumentNEIV1OperationCompleted;
        
        private System.Threading.SendOrPostCallback NEIHmaGuideV1OperationCompleted;
        
        private System.Threading.SendOrPostCallback NEIInitiationFormV1OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ITPCloudService() {
            this.Url = global::TestingKofaxIssues.Properties.Settings.Default.TestingKofaxIssues_neikofaxccmdev_ITPCloudService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateDocumentNEIV1CompletedEventHandler CreateDocumentNEIV1Completed;
        
        /// <remarks/>
        public event NEIHmaGuideV1CompletedEventHandler NEIHmaGuideV1Completed;
        
        /// <remarks/>
        public event NEIInitiationFormV1CompletedEventHandler NEIInitiationFormV1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.aiasoftware.com/cloud/v1/createdocumentnei/v1", RequestElementName="CreateDocumentNEIV1Request", RequestNamespace="http://www.aiasoftware.com/cloud/v1", ResponseNamespace="http://www.aiasoftware.com/cloud/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestinfo")]
        public CreateDocumentNEIV1ResponseRequestinfo CreateDocumentNEIV1(string partner, string customer, string contracttypename, string contracttypeversion, string jobid, string tid, string project, string docutemplate, string docutemplateemail, string docutemplatevcard, string publishstatus) {
            object[] results = this.Invoke("CreateDocumentNEIV1", new object[] {
                        partner,
                        customer,
                        contracttypename,
                        contracttypeversion,
                        jobid,
                        tid,
                        project,
                        docutemplate,
                        docutemplateemail,
                        docutemplatevcard,
                        publishstatus});
            return ((CreateDocumentNEIV1ResponseRequestinfo)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDocumentNEIV1Async(string partner, string customer, string contracttypename, string contracttypeversion, string jobid, string tid, string project, string docutemplate, string docutemplateemail, string docutemplatevcard, string publishstatus) {
            this.CreateDocumentNEIV1Async(partner, customer, contracttypename, contracttypeversion, jobid, tid, project, docutemplate, docutemplateemail, docutemplatevcard, publishstatus, null);
        }
        
        /// <remarks/>
        public void CreateDocumentNEIV1Async(string partner, string customer, string contracttypename, string contracttypeversion, string jobid, string tid, string project, string docutemplate, string docutemplateemail, string docutemplatevcard, string publishstatus, object userState) {
            if ((this.CreateDocumentNEIV1OperationCompleted == null)) {
                this.CreateDocumentNEIV1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDocumentNEIV1OperationCompleted);
            }
            this.InvokeAsync("CreateDocumentNEIV1", new object[] {
                        partner,
                        customer,
                        contracttypename,
                        contracttypeversion,
                        jobid,
                        tid,
                        project,
                        docutemplate,
                        docutemplateemail,
                        docutemplatevcard,
                        publishstatus}, this.CreateDocumentNEIV1OperationCompleted, userState);
        }
        
        private void OnCreateDocumentNEIV1OperationCompleted(object arg) {
            if ((this.CreateDocumentNEIV1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDocumentNEIV1Completed(this, new CreateDocumentNEIV1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.aiasoftware.com/cloud/v1/neihmaguide/v1", RequestElementName="NEIHmaGuideV1Request", RequestNamespace="http://www.aiasoftware.com/cloud/v1", ResponseNamespace="http://www.aiasoftware.com/cloud/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestinfo")]
        public NEIHmaGuideV1ResponseRequestinfo NEIHmaGuideV1(string partner, string customer, string contracttypename, string contracttypeversion, string jobid, string tid, string project, string docutemplate, string publishstatus, string developer, string requesttype) {
            object[] results = this.Invoke("NEIHmaGuideV1", new object[] {
                        partner,
                        customer,
                        contracttypename,
                        contracttypeversion,
                        jobid,
                        tid,
                        project,
                        docutemplate,
                        publishstatus,
                        developer,
                        requesttype});
            return ((NEIHmaGuideV1ResponseRequestinfo)(results[0]));
        }
        
        /// <remarks/>
        public void NEIHmaGuideV1Async(string partner, string customer, string contracttypename, string contracttypeversion, string jobid, string tid, string project, string docutemplate, string publishstatus, string developer, string requesttype) {
            this.NEIHmaGuideV1Async(partner, customer, contracttypename, contracttypeversion, jobid, tid, project, docutemplate, publishstatus, developer, requesttype, null);
        }
        
        /// <remarks/>
        public void NEIHmaGuideV1Async(string partner, string customer, string contracttypename, string contracttypeversion, string jobid, string tid, string project, string docutemplate, string publishstatus, string developer, string requesttype, object userState) {
            if ((this.NEIHmaGuideV1OperationCompleted == null)) {
                this.NEIHmaGuideV1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnNEIHmaGuideV1OperationCompleted);
            }
            this.InvokeAsync("NEIHmaGuideV1", new object[] {
                        partner,
                        customer,
                        contracttypename,
                        contracttypeversion,
                        jobid,
                        tid,
                        project,
                        docutemplate,
                        publishstatus,
                        developer,
                        requesttype}, this.NEIHmaGuideV1OperationCompleted, userState);
        }
        
        private void OnNEIHmaGuideV1OperationCompleted(object arg) {
            if ((this.NEIHmaGuideV1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NEIHmaGuideV1Completed(this, new NEIHmaGuideV1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.aiasoftware.com/cloud/v1/neiinitiationform/v1", RequestElementName="NEIInitiationFormV1Request", RequestNamespace="http://www.aiasoftware.com/cloud/v1", ResponseNamespace="http://www.aiasoftware.com/cloud/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestinfo")]
        public NEIInitiationFormV1ResponseRequestinfo NEIInitiationFormV1(string partner, string customer, string contracttypename, string contracttypeversion, string jobid, string ccode, string project, string docutemplate, string publishstatus, string developer) {
            object[] results = this.Invoke("NEIInitiationFormV1", new object[] {
                        partner,
                        customer,
                        contracttypename,
                        contracttypeversion,
                        jobid,
                        ccode,
                        project,
                        docutemplate,
                        publishstatus,
                        developer});
            return ((NEIInitiationFormV1ResponseRequestinfo)(results[0]));
        }
        
        /// <remarks/>
        public void NEIInitiationFormV1Async(string partner, string customer, string contracttypename, string contracttypeversion, string jobid, string ccode, string project, string docutemplate, string publishstatus, string developer) {
            this.NEIInitiationFormV1Async(partner, customer, contracttypename, contracttypeversion, jobid, ccode, project, docutemplate, publishstatus, developer, null);
        }
        
        /// <remarks/>
        public void NEIInitiationFormV1Async(string partner, string customer, string contracttypename, string contracttypeversion, string jobid, string ccode, string project, string docutemplate, string publishstatus, string developer, object userState) {
            if ((this.NEIInitiationFormV1OperationCompleted == null)) {
                this.NEIInitiationFormV1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnNEIInitiationFormV1OperationCompleted);
            }
            this.InvokeAsync("NEIInitiationFormV1", new object[] {
                        partner,
                        customer,
                        contracttypename,
                        contracttypeversion,
                        jobid,
                        ccode,
                        project,
                        docutemplate,
                        publishstatus,
                        developer}, this.NEIInitiationFormV1OperationCompleted, userState);
        }
        
        private void OnNEIInitiationFormV1OperationCompleted(object arg) {
            if ((this.NEIInitiationFormV1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NEIInitiationFormV1Completed(this, new NEIInitiationFormV1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aiasoftware.com/cloud/v1")]
    public partial class CreateDocumentNEIV1ResponseRequestinfo {
        
        private string partnerField;
        
        private string customerField;
        
        private string contracttypenameField;
        
        private string contracttypeversionField;
        
        private string jobidField;
        
        /// <remarks/>
        public string partner {
            get {
                return this.partnerField;
            }
            set {
                this.partnerField = value;
            }
        }
        
        /// <remarks/>
        public string customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public string contracttypename {
            get {
                return this.contracttypenameField;
            }
            set {
                this.contracttypenameField = value;
            }
        }
        
        /// <remarks/>
        public string contracttypeversion {
            get {
                return this.contracttypeversionField;
            }
            set {
                this.contracttypeversionField = value;
            }
        }
        
        /// <remarks/>
        public string jobid {
            get {
                return this.jobidField;
            }
            set {
                this.jobidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aiasoftware.com/cloud/v1")]
    public partial class NEIHmaGuideV1ResponseRequestinfo {
        
        private string partnerField;
        
        private string customerField;
        
        private string contracttypenameField;
        
        private string contracttypeversionField;
        
        private string jobidField;
        
        /// <remarks/>
        public string partner {
            get {
                return this.partnerField;
            }
            set {
                this.partnerField = value;
            }
        }
        
        /// <remarks/>
        public string customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public string contracttypename {
            get {
                return this.contracttypenameField;
            }
            set {
                this.contracttypenameField = value;
            }
        }
        
        /// <remarks/>
        public string contracttypeversion {
            get {
                return this.contracttypeversionField;
            }
            set {
                this.contracttypeversionField = value;
            }
        }
        
        /// <remarks/>
        public string jobid {
            get {
                return this.jobidField;
            }
            set {
                this.jobidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aiasoftware.com/cloud/v1")]
    public partial class NEIInitiationFormV1ResponseRequestinfo {
        
        private string partnerField;
        
        private string customerField;
        
        private string contracttypenameField;
        
        private string contracttypeversionField;
        
        private string jobidField;
        
        /// <remarks/>
        public string partner {
            get {
                return this.partnerField;
            }
            set {
                this.partnerField = value;
            }
        }
        
        /// <remarks/>
        public string customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public string contracttypename {
            get {
                return this.contracttypenameField;
            }
            set {
                this.contracttypenameField = value;
            }
        }
        
        /// <remarks/>
        public string contracttypeversion {
            get {
                return this.contracttypeversionField;
            }
            set {
                this.contracttypeversionField = value;
            }
        }
        
        /// <remarks/>
        public string jobid {
            get {
                return this.jobidField;
            }
            set {
                this.jobidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CreateDocumentNEIV1CompletedEventHandler(object sender, CreateDocumentNEIV1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDocumentNEIV1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDocumentNEIV1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateDocumentNEIV1ResponseRequestinfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateDocumentNEIV1ResponseRequestinfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void NEIHmaGuideV1CompletedEventHandler(object sender, NEIHmaGuideV1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NEIHmaGuideV1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NEIHmaGuideV1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NEIHmaGuideV1ResponseRequestinfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NEIHmaGuideV1ResponseRequestinfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void NEIInitiationFormV1CompletedEventHandler(object sender, NEIInitiationFormV1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NEIInitiationFormV1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NEIInitiationFormV1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NEIInitiationFormV1ResponseRequestinfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NEIInitiationFormV1ResponseRequestinfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591